# Pandas Analytics - Example 2

In [36]:
import pandas as pd

Read the file parking.csv into a dataframe
It contains historical information about the available parking spots in 6 city parking garages in Gent

Drop lines with duplicate "LastModified" field and keep the last line

Read the file holidays.csv into a dataframe
It contains the official school holidays
Show the first 5 lines

         date
0  2017-12-23
1  2017-12-24
2  2017-12-25
3  2017-12-26
4  2017-12-27

Add a column date to the parking dataframe that contains the date (no hours minutes or seconds). 
This column will look the same as the column date from the dataframe holidays

,LastModified,Name,Available,Capacity,Open,date
0,2018-10-24 23:38:00,P01 Vrijdagmarkt,430,647,True,2018-10-24
1,2018-10-24 23:38:00,P08 Ramen,147,266,True,2018-10-24
2,2018-10-24 23:38:00,P02 Reep,383,470,True,2018-10-24
3,2018-10-24 23:34:00,P10 Sint-Pietersplein,575,708,True,2018-10-24
4,2018-10-24 23:43:00,P01 Vrijdagmarkt,433,647,True,2018-10-24

Add a column holiday = 1 to the dataset holidays

         date  holiday
0  2017-12-23        1
1  2017-12-24        1
2  2017-12-25        1
3  2017-12-26        1
4  2017-12-27        1

Merge both datasets

,LastModified,Name,Available,Capacity,Open,date,holiday
0,2018-10-24 23:38:00,P01 Vrijdagmarkt,430,647,True,2018-10-24,NaN
1,2018-10-24 23:38:00,P08 Ramen,147,266,True,2018-10-24,NaN
2,2018-10-24 23:38:00,P02 Reep,383,470,True,2018-10-24,NaN
3,2018-10-24 23:34:00,P10 Sint-Pietersplein,575,708,True,2018-10-24,NaN
4,2018-10-24 23:43:00,P01 Vrijdagmarkt,433,647,True,2018-10-24,NaN

Filter the rows where holiday = 1

,LastModified,Name,Available,Capacity,Open,date,holiday
1029,2018-10-27 00:14:00,P07 Sint-Michiels,196,450,True,2018-10-27,1.0
1030,2018-10-27 00:14:00,P10 Sint-Pietersplein,555,708,True,2018-10-27,1.0
1031,2018-10-27 00:13:00,P01 Vrijdagmarkt,208,647,True,2018-10-27,1.0
1032,2018-10-27 00:14:00,P04 Savaanstraat,521,540,True,2018-10-27,1.0
1033,2018-10-27 00:13:00,P08 Ramen,52,266,True,2018-10-27,1.0
1034,2018-10-27 00:12:00,P02 Reep,335,470,True,2018-10-27,1.0
1035,2018-10-27 00:29:00,P07 Sint-Michiels,206,450,True,2018-10-27,1.0
1036,2018-10-27 00:29:00,P10 Sint-Pietersplein,560,708,True,2018-10-27,1.0
1037,2018-10-27 00:28:00,P01 Vrijdagmarkt,234,647,True,2018-10-27,1.0
1038,2018-10-27 00:27:00,P04 Savaanstraat,523,540,True,2018-10-27,1.0
1039,2018-10-27 00:29:00,P08 Ramen,59,266,True,2018-10-27,1.0
1040,2018-10-27 00:28:00,P02 Reep,340,470,True,2018-10-27,1.0
1041,2018-10-27 00:43:00,P07 Sint-Michiels,221,450,True,2018-10-27,1.0
1042,2018-10-27 00:44:00,P10 Sint-Pietersplein,568,708,True,2018-10-27,1.0
1043,2018-10-27 00:44:00,P01 Vrijdagmarkt,249,647,True,2018-10-27,1.0
1044,2018-10-27 00:42:00,P04 Savaanstraat,525,540,True,2018-10-27,1.0
1045,2018-10-27 00:34:00,P08 Ramen,59,266,True,2018-10-27,1.0
1046,2018-10-27 00:44:00,P02 Reep,353,470,True,2018-10-27,1.0
1047,2018-10-27 00:57:00,P07 Sint-Michiels,234,450,True,2018-10-27,1.0
1048,2018-10-27 00:57:00,P10 Sint-Pietersplein,582,708,True,2018-10-27,1.0
1049,2018-10-27 00:58:00,P01 Vrijdagmarkt,279,647,True,2018-10-27,1.0
1050,2018-10-27 00:55:00,P04 Savaanstraat,529,540,True,2018-10-27,1.0
1051,2018-10-27 00:56:00,P08 Ramen,62,266,True,2018-10-27,1.0
1052,2018-10-27 00:59:00,P02 Reep,363,470,True,2018-10-27,1.0
1053,2018-10-27 01:14:00,P07 Sint-Michiels,239,450,True,2018-10-27,1.0
1054,2018-10-27 01:14:00,P10 Sint-Pietersplein,605,708,True,2018-10-27,1.0
1055,2018-10-27 01:13:00,P01 Vrijdagmarkt,303,647,True,2018-10-27,1.0
1056,2018-10-27 01:14:00,P04 Savaanstraat,534,540,True,2018-10-27,1.0
1057,2018-10-27 01:06:00,P08 Ramen,64,266,True,2018-10-27,1.0
1058,2018-10-27 01:11:00,P02 Reep,367,470,True,2018-10-27,1.0
...,...,...,...,...,...,...,...
2350,2018-10-29 14:14:00,P07 Sint-Michiels,122,450,True,2018-10-29,1.0
2351,2018-10-29 14:14:00,P10 Sint-Pietersplein,287,708,True,2018-10-29,1.0
2352,2018-10-29 14:14:00,P01 Vrijdagmarkt,71,647,True,2018-10-29,1.0
2353,2018-10-29 14:13:00,P04 Savaanstraat,233,540,True,2018-10-29,1.0
2354,2018-10-29 14:13:00,P08 Ramen,82,266,True,2018-10-29,1.0
2355,2018-10-29 14:13:00,P02 Reep,286,470,True,2018-10-29,1.0
2356,2018-10-29 14:27:00,P07 Sint-Michiels,119,450,True,2018-10-29,1.0
2357,2018-10-29 14:29:00,P10 Sint-Pietersplein,275,708,True,2018-10-29,1.0
2358,2018-10-29 14:29:00,P01 Vrijdagmarkt,95,647,True,2018-10-29,1.0
2359,2018-10-29 14:29:00,P04 Savaanstraat,227,540,True,2018-10-29,1.0
2360,2018-10-29 14:29:00,P08 Ramen,82,266,True,2018-10-29,1.0
2361,2018-10-29 14:28:00,P02 Reep,275,470,True,2018-10-29,1.0
2362,2018-10-29 14:35:00,P07 Sint-Michiels,109,450,True,2018-10-29,1.0
2363,2018-10-29 14:36:00,P10 Sint-Pietersplein,262,708,True,2018-10-29,1.0
2364,2018-10-29 14:37:00,P01 Vrijdagmarkt,111,647,True,2018-10-29,1.0
2365,2018-10-29 14:36:00,P04 Savaanstraat,227,540,True,2018-10-29,1.0
2366,2018-10-29 14:37:00,P08 Ramen,81,266,True,2018-10-29,1.0
2367,2018-10-29 14:36:00,P02 Reep,273,470,True,2018-10-29,1.0
2368,2018-10-29 14:44:00,P07 Sint-Michiels,111,450,True,2018-10-29,1.0
2369,2018-10-29 14:44:00,P10 Sint-Pietersplein,262,708,True,2018-10-29,1.0
2370,2018-10-29 14:44:00,P01 Vrijdagmarkt,104,647,True,2018-10-29,1.0
2371,2018-10-29 14:44:00,P04 Savaanstraat,235,540,True,2018-10-29,1.0
2372,2018-10-29 14:44:00,P08 Ramen,84,266,True,2018-10-29,1.0
2373,2018-10-29 14:44:00,P02 Reep,269,470,True,2018-10-29,1.0
2374,2018-10-29 14:59:00,P07 Sint-Michiels,124,450,True,2018-10-29,1.0
2375,2018-10-29 14:59:00,P10 Sint-Pietersplein,261,708,True,2018-10-29,1.0
2376,2018-10-29 14:59:00,P01 Vrijdagmarkt,106,647,True,2018-10-29,1.0
2377,2018-10-29 14:57:00,P04 Savaanstraat,236,540,True,2018-10-29,1.0
2378,2018-10-29 14:56:00,P08 Ramen,83,266,True,2018-10-29,1.0
2379,2018-10-29 14:56:00,P02 Reep,269,470,True,2018-10-29,1.0

Replace the NaN in column holiday by 0

,LastModified,Name,Available,Capacity,Open,date,holiday
0,2018-10-24 23:38:00,P01 Vrijdagmarkt,430,647,True,2018-10-24,0.0
1,2018-10-24 23:38:00,P08 Ramen,147,266,True,2018-10-24,0.0
2,2018-10-24 23:38:00,P02 Reep,383,470,True,2018-10-24,0.0
3,2018-10-24 23:34:00,P10 Sint-Pietersplein,575,708,True,2018-10-24,0.0
4,2018-10-24 23:43:00,P01 Vrijdagmarkt,433,647,True,2018-10-24,0.0
5,2018-10-24 23:38:00,P07 Sint-Michiels,284,450,True,2018-10-24,0.0
6,2018-10-24 23:44:00,P10 Sint-Pietersplein,574,708,True,2018-10-24,0.0
7,2018-10-24 23:44:00,P01 Vrijdagmarkt,434,647,True,2018-10-24,0.0
8,2018-10-24 23:39:00,P04 Savaanstraat,521,540,True,2018-10-24,0.0
9,2018-10-24 23:42:00,P08 Ramen,148,266,True,2018-10-24,0.0
10,2018-10-24 23:43:00,P02 Reep,386,470,True,2018-10-24,0.0
11,2018-10-25 00:14:00,P07 Sint-Michiels,304,450,True,2018-10-25,0.0
12,2018-10-25 00:12:00,P10 Sint-Pietersplein,578,708,True,2018-10-25,0.0
13,2018-10-25 00:14:00,P01 Vrijdagmarkt,456,647,True,2018-10-25,0.0
14,2018-10-25 00:10:00,P04 Savaanstraat,535,540,True,2018-10-25,0.0
15,2018-10-25 00:01:00,P08 Ramen,155,266,True,2018-10-25,0.0
16,2018-10-25 00:10:00,P02 Reep,389,470,True,2018-10-25,0.0
17,2018-10-25 00:26:00,P07 Sint-Michiels,307,450,True,2018-10-25,0.0
18,2018-10-25 00:25:00,P10 Sint-Pietersplein,584,708,True,2018-10-25,0.0
19,2018-10-25 00:27:00,P01 Vrijdagmarkt,466,647,True,2018-10-25,0.0
20,2018-10-25 00:22:00,P04 Savaanstraat,537,540,True,2018-10-25,0.0
21,2018-10-25 00:24:00,P08 Ramen,155,266,True,2018-10-25,0.0
22,2018-10-25 00:25:00,P02 Reep,391,470,True,2018-10-25,0.0
23,2018-10-25 00:40:00,P07 Sint-Michiels,310,450,True,2018-10-25,0.0
24,2018-10-25 00:44:00,P01 Vrijdagmarkt,471,647,True,2018-10-25,0.0
25,2018-10-25 00:40:00,P04 Savaanstraat,539,540,True,2018-10-25,0.0
26,2018-10-25 00:44:00,P08 Ramen,161,266,True,2018-10-25,0.0
27,2018-10-25 00:50:00,P07 Sint-Michiels,313,450,True,2018-10-25,0.0
28,2018-10-25 00:43:00,P10 Sint-Pietersplein,589,708,True,2018-10-25,0.0
29,2018-10-25 00:58:00,P01 Vrijdagmarkt,474,647,True,2018-10-25,0.0
...,...,...,...,...,...,...,...
2350,2018-10-29 14:14:00,P07 Sint-Michiels,122,450,True,2018-10-29,1.0
2351,2018-10-29 14:14:00,P10 Sint-Pietersplein,287,708,True,2018-10-29,1.0
2352,2018-10-29 14:14:00,P01 Vrijdagmarkt,71,647,True,2018-10-29,1.0
2353,2018-10-29 14:13:00,P04 Savaanstraat,233,540,True,2018-10-29,1.0
2354,2018-10-29 14:13:00,P08 Ramen,82,266,True,2018-10-29,1.0
2355,2018-10-29 14:13:00,P02 Reep,286,470,True,2018-10-29,1.0
2356,2018-10-29 14:27:00,P07 Sint-Michiels,119,450,True,2018-10-29,1.0
2357,2018-10-29 14:29:00,P10 Sint-Pietersplein,275,708,True,2018-10-29,1.0
2358,2018-10-29 14:29:00,P01 Vrijdagmarkt,95,647,True,2018-10-29,1.0
2359,2018-10-29 14:29:00,P04 Savaanstraat,227,540,True,2018-10-29,1.0
2360,2018-10-29 14:29:00,P08 Ramen,82,266,True,2018-10-29,1.0
2361,2018-10-29 14:28:00,P02 Reep,275,470,True,2018-10-29,1.0
2362,2018-10-29 14:35:00,P07 Sint-Michiels,109,450,True,2018-10-29,1.0
2363,2018-10-29 14:36:00,P10 Sint-Pietersplein,262,708,True,2018-10-29,1.0
2364,2018-10-29 14:37:00,P01 Vrijdagmarkt,111,647,True,2018-10-29,1.0
2365,2018-10-29 14:36:00,P04 Savaanstraat,227,540,True,2018-10-29,1.0
2366,2018-10-29 14:37:00,P08 Ramen,81,266,True,2018-10-29,1.0
2367,2018-10-29 14:36:00,P02 Reep,273,470,True,2018-10-29,1.0
2368,2018-10-29 14:44:00,P07 Sint-Michiels,111,450,True,2018-10-29,1.0
2369,2018-10-29 14:44:00,P10 Sint-Pietersplein,262,708,True,2018-10-29,1.0
2370,2018-10-29 14:44:00,P01 Vrijdagmarkt,104,647,True,2018-10-29,1.0
2371,2018-10-29 14:44:00,P04 Savaanstraat,235,540,True,2018-10-29,1.0
2372,2018-10-29 14:44:00,P08 Ramen,84,266,True,2018-10-29,1.0
2373,2018-10-29 14:44:00,P02 Reep,269,470,True,2018-10-29,1.0
2374,2018-10-29 14:59:00,P07 Sint-Michiels,124,450,True,2018-10-29,1.0
2375,2018-10-29 14:59:00,P10 Sint-Pietersplein,261,708,True,2018-10-29,1.0
2376,2018-10-29 14:59:00,P01 Vrijdagmarkt,106,647,True,2018-10-29,1.0
2377,2018-10-29 14:57:00,P04 Savaanstraat,236,540,True,2018-10-29,1.0
2378,2018-10-29 14:56:00,P08 Ramen,83,266,True,2018-10-29,1.0
2379,2018-10-29 14:56:00,P02 Reep,269,470,True,2018-10-29,1.0